# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface

hardware_interface:
  joints:
    - axis_1
    - axis_2
    - axis_3
    - axis_4
    - axis_5
    - axis_6
    - l_finger
    - r_finger

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - axis_1
    - axis_2
    - axis_3
    - axis_4
    - axis_5
    - axis_6

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10

controller_list:
    - name: manipulator_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - axis_1
        - axis_2
        - axis_3
        - axis_4
        - axis_5
        - axis_6