name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main, TARGET_WORKSPACE: 'github:burkap/rover_utils#main github:wjwwood/serial#main github:PickNikRobotics/ros_control_boilerplate#melodic-devel'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
